bombulator.register_nodes {
    ["nodes_nature:sand"] = { chance = 1.0 },
    ["nodes_nature:silt"] = { chance = 1.0 },
    ["nodes_nature:clay"] = { chance = 1.0 },
    ["nodes_nature:gravel"] = { chance = 1.0 },
    ["nodes_nature:loam"] = { chance = 1.0 },
    ["nodes_nature:volcanic_ash"] = { chance = 1.0 },

    ["nodes_nature:woodland_soil"] = { chance = 1.0 },
    ["nodes_nature:marshland_soil"] = { chance = 1.0 },
    ["nodes_nature:grassland_soil"] = { chance = 1.0 },
    ["nodes_nature:duneland_soil"] = { chance = 1.0 },
    ["nodes_nature:highland_soil"] = { chance = 1.0 },
    ["nodes_nature:grassland_barren_soil"] = { chance = 1.0 },
    ["nodes_nature:woodland_dry_soil"] = { chance = 1.0 },

    ["nodes_nature:sandstone"] = { chance = 1.0 },
    ["nodes_nature:siltstone"] = { chance = 1.0 },
    ["nodes_nature:claystone"] = { chance = 1.0 },
    ["nodes_nature:conglomerate"] = { chance = 1.0 },

    ["nodes_nature:limestone"] = { chance = 1.0 },
    ["nodes_nature:ironstone"] = { chance = 1.0 },
    ["nodes_nature:granite"] = { chance = 1.0 },
    ["nodes_nature:basalt"] = { chance = 1.0 },
    ["nodes_nature:gneiss"] = { chance = 1.0 },
    ["nodes_nature:jade"] = { chance = 1.0 },

    ["nodes_nature:maraka_tree"] = { chance = 1.0 },
    ["nodes_nature:tangkal_tree"] = { chance = 1.0 },
    ["nodes_nature:sasaran_tree"] = { chance = 1.0 },
    ["nodes_nature:kagum_tree"] = { chance = 1.0 },
}

bombulator.register_textures {
    ["nodes_nature_ag_dep_top.png"] = { chance = 1.0 },
    ["nodes_nature_ag_top.png"] = { chance = 1.0 },
    ["nodes_nature_basalt.png"] = { chance = 1.0 },
    ["nodes_nature_clay.png"] = { chance = 1.0 },
    ["nodes_nature_claystone.png"] = { chance = 1.0 },
    ["nodes_nature_conglomerate_brick.png"] = { chance = 1.0 },
    ["nodes_nature_freshwater_flowing_animated.png"] = { chance = 1.0 },
    ["nodes_nature_freshwater.png"] = { chance = 1.0 },
    ["nodes_nature_lava.png"] = { chance = 1.0 },
    ["nodes_nature_kagum_tree_top.png"] = { chance = 1.0 },
    ["nodes_nature_maraka_log.png"] = { chance = 1.0 },
    ["nodes_nature_marshland_soil.png"] = { chance = 1.0 },
    ["nodes_nature_moss.png"] = { chance = 1.0 },
    ["nodes_nature_silt.png"] = { chance = 1.0 },
}