bombulator.register_nodes {
    ["default:stone"] = { chance = 1.0 },
    ["default:desert_stone"] = { chance = 1.0 },
    ["default:sandstone"] = { chance = 1.0 },
    ["default:obsidian"] = { chance = 1.0 },

    ["default:dirt"] = { chance = 1.0 },
    ["default:dirt_with_grass"] = { chance = 1.0 },
    ["default:dirt_with_grass_footsteps"] = { chance = 1.0 },
    ["default:dirt_with_dry_grass"] = { chance = 1.0 },
    ["default:dirt_with_snow"] = { chance = 1.0 },
    ["default:dirt_with_rainforest_litter"] = { chance = 1.0 },
    ["default:dirt_with_coniferous_litter"] = { chance = 1.0 },
    ["default:dry_dirt"] = { chance = 1.0 },
    ["default:dry_dirt_with_dry_grass"] = { chance = 1.0 },
    ["default:permafrost"] = { chance = 1.0 },
    ["default:permafrost_with_stones"] = { chance = 1.0 },
    ["default:permafrost_with_moss"] = { chance = 1.0 },
    ["default:sand"] = { chance = 1.0 },
    ["default:desert_sand"] = { chance = 1.0 },
    ["default:silver_sand"] = { chance = 1.0 },
    ["default:gravel"] = { chance = 1.0 },
    ["default:clay"] = { chance = 1.0 },
    ["default:snow"] = { chance = 1.0 },
    ["default:snowblock"] = { chance = 1.0 },
    ["default:ice"] = { chance = 1.0 },
    ["default:cave_ice"] = { chance = 1.0 },

    ["default:tree"] = { chance = 1.0 },
    ["default:jungletree"] = { chance = 1.0 },
    ["default:pine_tree"] = { chance = 1.0 },
    ["default:acacia_tree"] = { chance = 1.0 },
    ["default:aspen_tree"] = { chance = 1.0 },
    
    ["default:stone_with_coal"] = { chance = 1.0 },
    ["default:stone_with_iron"] = { chance = 1.0 },
    ["default:stone_with_copper"] = { chance = 1.0 },
    ["default:stone_with_tin"] = { chance = 1.0 },
    ["default:stone_with_gold"] = { chance = 1.0 },
    ["default:stone_with_mese"] = { chance = 1.0 },
    ["default:stone_with_diamond"] = { chance = 1.0 },

    ["default:cactus"] = { chance = 1.0 },
    ["default:papyrus"] = { chance = 1.0 },
    ["default:bush_leaves"] = { chance = 1.0 },
    ["default:acacia_bush_leaves"] = { chance = 1.0 },
    ["default:pine_bush_needles"] = { chance = 1.0 },
    ["default:blueberry_bush_leaves_with_berries"] = { chance = 1.0 },
    ["default:blueberry_bush_leaves"] = { chance = 1.0 },
    ["default:sand_with_kelp"] = { chance = 1.0 },

    ["default:coral_green"] = { chance = 1.0 },
    ["default:coral_pink"] = { chance = 1.0 },
    ["default:coral_cyan"] = { chance = 1.0 },
    ["default:coral_brown"] = { chance = 1.0 },
    ["default:coral_orange"] = { chance = 1.0 },
    ["default:coral_skeleton"] = { chance = 1.0 },

    ["default:cloud"] = { chance = 1.0 },
}