bombulator.register_nodes {
    ["mcl_core:stone"] = { chance = 1.0 },
    ["mcl_core:stone_with_coal"] = { chance = 1.0 },
    ["mcl_core:stone_with_iron"] = { chance = 1.0 },
    ["mcl_core:stone_with_gold"] = { chance = 1.0 },
    ["mcl_core:stone_with_redstone"] = { chance = 1.0 },
    ["mcl_core:stone_with_redstone_lit"] = { chance = 1.0 },
    ["mcl_core:stone_with_lapis"] = { chance = 1.0 },
    ["mcl_core:stone_with_emerald"] = { chance = 1.0 },
    ["mcl_core:stone_with_diamond"] = { chance = 1.0 },
    ["mcl_core:granite"] = { chance = 1.0 },
    ["mcl_core:andesite"] = { chance = 1.0 },
    ["mcl_core:diorite"] = { chance = 1.0 },
    ["mcl_core:dirt_with_grass"] = { chance = 1.0 },
    ["mcl_core:dirt_with_grass_snow"] = { chance = 1.0 },
    ["mcl_core:dirt"] = { chance = 1.0 },
    ["mcl_core:mycelium"] = { chance = 1.0 },
    ["mcl_core:mycelium_snow"] = { chance = 1.0 },
    ["mcl_core:podzol"] = { chance = 1.0 },
    ["mcl_core:podzol_snow"] = { chance = 1.0 },
    ["mcl_core:coarse_dirt"] = { chance = 1.0 },
    ["mcl_core:gravel"] = { chance = 1.0 },
    ["mcl_core:sand"] = { chance = 1.0 },
    ["mcl_core:redsand"] = { chance = 1.0 },
    ["mcl_core:obsidian"] = { chance = 1.0 },
    ["mcl_core:ice"] = { chance = 1.0 },
    ["mcl_core:packed_ice"] = { chance = 1.0 },
    ["mcl_core:blue_ice"] = { chance = 1.0 },
    ["mcl_core:snow"] = { chance = 1.0 },
}

bombulator.register_textures {
    ["extra_mobs_cod.png"] = { chance = 1.0 },
    ["extra_mobs_dolphin.png"] = { chance = 1.0 },
    ["extra_mobs_glow_squid.png"] = { chance = 1.0 },
    ["extra_mobs_hoglin.png"] = { chance = 1.0 },
    ["extra_mobs_piglin.png"] = { chance = 1.0 },
    ["extra_mobs_piglin_brute.png"] = { chance = 1.0 },
    ["mobs_mc_creeper.png"] = { chance = 1.0 },
    ["mobs_mc_drowned.png"] = { chance = 1.0 },

    ["mcl_pantings_paintings.png"] = { chance = 1.0 },
    ["mcl_pantings_painting.png"] = { chance = 1.0 },

    ["default_acacia_leaves.png"] = { chance = 1.0 },
    ["default_brick.png"] = { chance = 1.0 },
    ["default_clay.png"] = { chance = 1.0 },
    ["default_cobble.png"] = { chance = 1.0 },
    ["default_dirt.png"] = { chance = 1.0 },
    ["default_gold_block.png"] = { chance = 1.0 },
    ["default_gravel.png"] = { chance = 1.0 },
    ["default_ice.png"] = { chance = 1.0 },
    ["default_stone.png"] = { chance = 1.0 },
}