bombulator.register_nodes {
    ["default:stone"] = { chance = 1.0 },
    ["default:desert_stone"] = { chance = 1.0 },
    ["default:sandstone"] = { chance = 1.0 },
    ["default:obsidian"] = { chance = 1.0 },

    ["default:dirt"] = { chance = 1.0 },
    ["default:dirt_with_grass"] = { chance = 1.0 },
    ["default:dirt_with_grass_footsteps"] = { chance = 1.0 },
    ["default:dirt_with_dry_grass"] = { chance = 1.0 },
    ["default:dirt_with_snow"] = { chance = 1.0 },
    ["default:dirt_with_rainforest_litter"] = { chance = 1.0 },
    ["default:dirt_with_coniferous_litter"] = { chance = 1.0 },
    ["default:dry_dirt"] = { chance = 1.0 },
    ["default:dry_dirt_with_dry_grass"] = { chance = 1.0 },
    ["default:permafrost"] = { chance = 1.0 },
    ["default:permafrost_with_stones"] = { chance = 1.0 },
    ["default:permafrost_with_moss"] = { chance = 1.0 },
    ["default:sand"] = { chance = 1.0 },
    ["default:desert_sand"] = { chance = 1.0 },
    ["default:silver_sand"] = { chance = 1.0 },
    ["default:gravel"] = { chance = 1.0 },
    ["default:clay"] = { chance = 1.0 },
    ["default:snow"] = { chance = 1.0 },
    ["default:snowblock"] = { chance = 1.0 },
    ["default:ice"] = { chance = 1.0 },
    ["default:cave_ice"] = { chance = 1.0 },

    ["default:tree"] = { chance = 1.0 },
    ["default:jungletree"] = { chance = 1.0 },
    ["default:pine_tree"] = { chance = 1.0 },
    ["default:acacia_tree"] = { chance = 1.0 },
    ["default:aspen_tree"] = { chance = 1.0 },
    
    ["default:stone_with_coal"] = { chance = 1.0 },
    ["default:stone_with_iron"] = { chance = 1.0 },
    ["default:stone_with_copper"] = { chance = 1.0 },
    ["default:stone_with_tin"] = { chance = 1.0 },
    ["default:stone_with_gold"] = { chance = 1.0 },
    ["default:stone_with_mese"] = { chance = 1.0 },
    ["default:stone_with_diamond"] = { chance = 1.0 },

    ["default:cactus"] = { chance = 1.0 },
    ["default:papyrus"] = { chance = 1.0 },
    ["default:bush_leaves"] = { chance = 1.0 },
    ["default:acacia_bush_leaves"] = { chance = 1.0 },
    ["default:pine_bush_needles"] = { chance = 1.0 },
    ["default:blueberry_bush_leaves_with_berries"] = { chance = 1.0 },
    ["default:blueberry_bush_leaves"] = { chance = 1.0 },
    ["default:sand_with_kelp"] = { chance = 1.0 },

    ["default:coral_green"] = { chance = 1.0 },
    ["default:coral_pink"] = { chance = 1.0 },
    ["default:coral_cyan"] = { chance = 1.0 },
    ["default:coral_brown"] = { chance = 1.0 },
    ["default:coral_orange"] = { chance = 1.0 },
    ["default:coral_skeleton"] = { chance = 1.0 },

    ["default:cloud"] = { chance = 1.0 },

    ["default:furnace"] = { chance = 0.5 },

    ["default:chest"] = { chance = 0.5 },
    ["default:chest_locked"] = { chance = 1.0 },
}

bombulator.register_sounds {
    ["default_break_glass"] = { chance = 1.0 },
    
    ["default_chest_close"] = { chance = 1.0 },
    ["default_chest_open"] = { chance = 1.0 },
    ["default_furnace_active"] = { chance = 1.0 },

    ["default_cool_lava"] = { chance = 1.0 },

    ["default_dig_choppy"] = { chance = 1.0 },
    ["default_dig_cracky"] = { chance = 1.0 },
    ["default_dig_crumbly"] = { chance = 1.0 },
    ["default_dig_dig_immediate"] = { chance = 1.0 },
    ["default_dig_metal"] = { chance = 1.0 },
    ["default_dig_oddly_breakable_by_hand"] = { chance = 1.0 },
    ["default_dig_snappy"] = { chance = 1.0 },
    ["default_gravel_dig"] = { chance = 1.0 },
    ["default_ice_dig"] = { chance = 1.0 },

    ["default_dug_metal"] = { chance = 1.0 },
    ["default_dug_node"] = { chance = 1.0 },
    ["default_gravel_dug"] = { chance = 1.0 },
    ["default_ice_dug"] = { chance = 1.0 },

    ["default_dirt_footstep"] = { chance = 1.0 },
    ["default_hard_footstep"] = { chance = 1.0 },
    ["default_glass_footstep"] = { chance = 1.0 },
    ["default_grass_footstep"] = { chance = 1.0 },
    ["default_gravel_footstep"] = { chance = 1.0 },
    ["default_ice_footstep"] = { chance = 1.0 },
    ["default_metal_footstep"] = { chance = 1.0 },
    ["default_sand_footstep"] = { chance = 1.0 },
    ["default_snow_footstep"] = { chance = 1.0 },
    ["default_water_footstep"] = { chance = 1.0 },
    ["default_wood_footstep"] = { chance = 1.0 },

    ["default_place_node"] = { chance = 1.0 },
    ["default_place_node_hard"] = { chance = 1.0 },
    ["default_place_node_metal"] = { chance = 1.0 },

    ["default_tool_breaks"] = { chance = 1.0 },
}

bombulator.register_textures {
    ["default_acacia_leaves.png"] = { chance = 1.0 },
    ["default_brick.png"] = { chance = 1.0 },
    ["default_clay.png"] = { chance = 1.0 },
    ["default_cobble.png"] = { chance = 1.0 },
    ["default_dirt.png"] = { chance = 1.0 },
    ["default_gold_block.png"] = { chance = 1.0 },
    ["default_gravel.png"] = { chance = 1.0 },
    ["default_ice.png"] = { chance = 1.0 },
    ["default_stone.png"] = { chance = 1.0 },
}